language: ruby

env:
  global:
    - secure: 'EYbHbyIzF+G1xFZZNuus5fLMwl+pRQGE7kinTEu7cEjzbcr428xqRcQ3J6EA 8z/DYxKWfkPY+9/wYI+b8FelVK9vByzcxScUWAmqPrhaLJkwlmkEVC3U//Rb weyYYZhDriNcnYHeAcVOSeaI3O9zR8+LGaD/Ju1qpQkHXdP2Y08='
    - POST_BUILD=true


script: 
    - ./build.sh
